version = 1

[common]
api_mode = false
api_access_token = "password"
default_url = [""]
enable_insert = true
insert_url = [""]
prepend_insert_url = true
exclude_remarks = ["(CFnat|Expire|QQ|Traffic|åˆ°æœŸ|è¿‡æœŸ|é‡ç½®|æµé‡|æ—¶é—´|å®˜ç½‘|äº§å“|å¹³å°|é¢‘é“)"]
enable_filter = false
base_path = "base"
clash_rule_base = "base/all_base.tpl"
surge_rule_base = "base/all_base.tpl"
surfboard_rule_base = "base/all_base.tpl"
mellow_rule_base = "base/all_base.tpl"
quan_rule_base = "base/all_base.tpl"
quanx_rule_base = "base/all_base.tpl"
loon_rule_base = "base/all_base.tpl"
sssub_rule_base = "base/all_base.tpl"
singbox_rule_base = "base/singbox.json"
proxy_config = "SYSTEM"
proxy_ruleset = "SYSTEM"
proxy_subscription = "NONE"
append_proxy_type = false
reload_conf_on_request = false

[node_pref]
sort_flag = false
filter_deprecated_nodes = false
append_sub_userinfo = true
clash_use_new_field_name = true
clash_proxies_style = "flow"
clash_proxy_groups_style = "block"
singbox_add_clash_modes = false

[[node_pref.rename_node]]
match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?å€ç‡?)|(x|X))\)?'
replace = "$1x"

[managed_config]
write_managed_config = true
managed_config_prefix = "http://127.0.0.1:25500"
config_update_interval = 86400
config_update_strict = false
quanx_device_id = ""

[surge_external_proxy]
resolve_hostname = true

[emojis]
add_emoji = true
remove_old_emoji = true

[[emojis.emoji]]
match = "(?i:Bandwidth|expire|æµé‡|æ—¶é—´|åº”æ€¥|è¿‡æœŸ)"
emoji = "ğŸ³ï¸â€ğŸŒˆ"

[[emojis.emoji]]
match = '(Emby)'
emoji = 'ğŸï¸'

[[emojis.emoji]]
match = "(?i:\\bHK[G]?\\d*\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]æ¸¯)"
emoji = "ğŸ‡­ğŸ‡°"

[[emojis.emoji]]
match = "(?i:\\bTW[N]?\\d*\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b)"
emoji = 'ğŸ‡¹ğŸ‡¼'

[[emojis.emoji]]
match = "(?i:\\bSG[P]?\\d*\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emojis.emoji]]
match = "(å°¼æ—¥åˆ©äºš|Nigeria)"
emoji = "ğŸ‡³ğŸ‡¬"

[[emojis.emoji]]
match = "(?i:\\bJP[N]?\\d*\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emojis.emoji]]
match = "(?i:(?<!North\\s)(\\bK[O]?R\\d*\\b|Korea|é¦–å°”|éŸ©|éŸ“))"
emoji = "ğŸ‡°ğŸ‡·"

[[emojis.emoji]]
match = "(?i:\\bUS[A]?\\d*\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"
emoji = "ğŸ‡ºğŸ‡¸"

[[emojis.emoji]]
match = "(Ascension|é˜¿æ£®æ¾)"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emojis.emoji]]
match = "(?i:\\bUAE\\b|Dubai|é˜¿è”é…‹|è¿ªæ‹œ)"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emojis.emoji]]
match = "(é˜¿å°”å·´å°¼äºš|Albania)"
emoji = "ğŸ‡¦ğŸ‡±"

[[emojis.emoji]]
match = "(å—æ|Antarctica)"
emoji = "ğŸ‡¦ğŸ‡¶"

[[emojis.emoji]]
match = "(Argentina|é˜¿æ ¹å»·)"
emoji = "ğŸ‡¦ğŸ‡·"

[[emojis.emoji]]
match = "(Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emojis.emoji]]
match = "(?i:\\bAU[S]?\\d*\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)"
emoji = "ğŸ‡¦ğŸ‡º"

[[emojis.emoji]]
match = "(é˜¿å¡æ‹œç–†|Azerbaijan)"
emoji = "ğŸ‡¦ğŸ‡¿"

[[emojis.emoji]]
match = "(æ³¢é»‘å…±å’Œå›½|æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³|Bosnia|Herzegovina)"
emoji = "ğŸ‡§ğŸ‡¦"

[[emojis.emoji]]
match = "(Belgium|æ¯”åˆ©æ—¶)"
emoji = "ğŸ‡§ğŸ‡ª"

[[emojis.emoji]]
match = "(ä¿åŠ åˆ©äºš|Bulgaria)"
emoji = "ğŸ‡§ğŸ‡¬"

[[emojis.emoji]]
match = "(Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)"
emoji = "ğŸ‡§ğŸ‡·"

[[emojis.emoji]]
match = "(?i:\\bCA[N]?\\d*\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emojis.emoji]]
match = "(Switzerland|Zurich|ç‘å£«|è‹é»ä¸–)"
emoji = "ğŸ‡¨ğŸ‡­"

[[emojis.emoji]]
match = "(æ™ºåˆ©|Chile)"
emoji = "ğŸ‡¨ğŸ‡±"

[[emojis.emoji]]
match = "(Colombia|å“¥ä¼¦æ¯”äºš)"
emoji = "ğŸ‡¨ğŸ‡´"

[[emojis.emoji]]
match = "(Costa Rica|å“¥æ–¯è¾¾é»åŠ )"
emoji = "ğŸ‡¨ğŸ‡·"

[[emojis.emoji]]
match = "(å¡æµ¦è·¯æ–¯|Cyprus)"
emoji = "ğŸ‡¨ğŸ‡¾"

[[emojis.emoji]]
match = "(Czech|æ·å…‹)"
emoji = "ğŸ‡¨ğŸ‡¿"

[[emojis.emoji]]
match = "(?i:\\bDE[U]?\\d*\\b|Germany|æ³•å…°å…‹ç¦|å¾·(å›½|æ„å¿—)|ä¸­å¾·|^å¾·$)"
emoji = "ğŸ‡©ğŸ‡ª"

[[emojis.emoji]]
match = "(?i:\\bD[N]?K\\b|Denmark|ä¸¹éº¦)"
emoji = "ğŸ‡©ğŸ‡°"

[[emojis.emoji]]
match = "(çˆ±æ²™å°¼äºš|Estonia)"
emoji = "ğŸ‡ªğŸ‡ª"

[[emojis.emoji]]
match = "(åŸƒåŠ|Egypt)"
emoji = "ğŸ‡ªğŸ‡¬"

[[emojis.emoji]]
match = "(?i:\\bES[P]?\\d*\\b|Spain|è¥¿ç­ç‰™)"
emoji = "ğŸ‡ªğŸ‡¸"

[[emojis.emoji]]
match = "(Europe|æ¬§æ´²)"
emoji = "ğŸ‡ªğŸ‡º"

[[emojis.emoji]]
match = "(Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº)"
emoji = "ğŸ‡«ğŸ‡®"

[[emojis.emoji]]
match = "(?i:\\bFR[A]?\\d*\\b|France|Paris|æ³•å›½|å·´é»)"
emoji = "ğŸ‡«ğŸ‡·"

[[emojis.emoji]]
match = "(?i:\\bUK\\d*\\b|\\bGB[R]?\\d*\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)"
emoji = "ğŸ‡¬ğŸ‡§"

[[emojis.emoji]]
match = "(å¸Œè…Š|Greece)"
emoji = "ğŸ‡¬ğŸ‡·"

[[emojis.emoji]]
match = "(æ ¼é²å‰äºš|Georgia)"
emoji = "ğŸ‡¬ğŸ‡ª"

[[emojis.emoji]]
match = "(å…‹ç½—åœ°äºš|Croatia)"
emoji = "ğŸ‡­ğŸ‡·"

[[emojis.emoji]]
match = "(Hungary|åŒˆç‰™åˆ©)"
emoji = "ğŸ‡­ğŸ‡º"

[[emojis.emoji]]
match = "(Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾)"
emoji = "ğŸ‡®ğŸ‡©"

[[emojis.emoji]]
match = "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)"
emoji = "ğŸ‡®ğŸ‡ª"

[[emojis.emoji]]
match = "(Israel|ä»¥è‰²åˆ—)"
emoji = "ğŸ‡®ğŸ‡±"

[[emojis.emoji]]
match = "(é©¬æ©å²›|Mann)"
emoji = "ğŸ‡®ğŸ‡²"

[[emojis.emoji]]
match = "(?i:\\bIN[D]?\\d*\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·)"
emoji = "ğŸ‡®ğŸ‡³"

[[emojis.emoji]]
match = "(ä¼Šæœ—|Iran)"
emoji = "ğŸ‡®ğŸ‡·"

[[emojis.emoji]]
match = "(?i:\\bIS[L]?\\d*\\b|Iceland|å†°å²›)"
emoji = "ğŸ‡®ğŸ‡¸"

[[emojis.emoji]]
match = "(Italy|Italia|Milan|æ„å¤§åˆ©|ç±³å…°)"
emoji = "ğŸ‡®ğŸ‡¹"

[[emojis.emoji]]
match = "(çº¦æ—¦|Jordan)"
emoji = "ğŸ‡¯ğŸ‡´"

[[emojis.emoji]]
match = "(è‚¯å°¼äºš|Kenya)"
emoji = "ğŸ‡°ğŸ‡ª"

[[emojis.emoji]]
match = "(å‰å°”å‰æ–¯æ–¯å¦|Kyrgyzstan)"
emoji = "ğŸ‡°ğŸ‡¬"

[[emojis.emoji]]
match = "(æŸ¬åŸ”å¯¨|Cambodia)"
emoji = "ğŸ‡°ğŸ‡­"

[[emojis.emoji]]
match = "(North.*?Korea|æœé²œ)"
emoji = "ğŸ‡°ğŸ‡µ"

[[emojis.emoji]]
match = "(å“ˆè¨å…‹æ–¯å¦|Kazakhstan)"
emoji = "ğŸ‡°ğŸ‡¿"

[[emojis.emoji]]
match = "(ç«‹é™¶å®›|Lietuvos)"
emoji = "ğŸ‡±ğŸ‡¹"

[[emojis.emoji]]
match = "(å¢æ£®å ¡|Luxemburg|Luxembourg)"
emoji = "ğŸ‡±ğŸ‡º"

[[emojis.emoji]]
match = "(æ‹‰è„±ç»´äºš|Latvia)"
emoji = "ğŸ‡±ğŸ‡»"

[[emojis.emoji]]
match = "(Moldova|æ‘©å°”å¤šç“¦)"
emoji = "ğŸ‡²ğŸ‡©"

[[emojis.emoji]]
match = "(åŒ—é©¬å…¶é¡¿|Macedonia)"
emoji = "ğŸ‡²ğŸ‡°"

[[emojis.emoji]]
match = "(ç¼…ç”¸|Myanmar)"
emoji = "ğŸ‡²ğŸ‡²"

[[emojis.emoji]]
match = "(è’™å¤|ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ|Mongolia)"
emoji = "ğŸ‡²ğŸ‡³"

[[emojis.emoji]]
match = "(Macao|æ¾³é—¨|\\bCTM\\b)"
emoji = "ğŸ‡²ğŸ‡´"

[[emojis.emoji]]
match = "(å¢¨è¥¿å“¥|Mexico)"
emoji = "ğŸ‡²ğŸ‡½"

[[emojis.emoji]]
match = "(Malaysia|é©¬æ¥|MY)"
emoji = "ğŸ‡²ğŸ‡¾"

[[emojis.emoji]]
match = "(?i:\\bNL[D]?\\d*\\b|Netherlands|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹)"
emoji = "ğŸ‡³ğŸ‡±"

[[emojis.emoji]]
match = "(æŒªå¨|Norway)"
emoji = "ğŸ‡³ğŸ‡´"

[[emojis.emoji]]
match = "(æ–°è¥¿å…°|çº½è¥¿å…°|New Zealand)"
emoji = "ğŸ‡³ğŸ‡¿"

[[emojis.emoji]]
match = "(?i:\\bP[O]?H\\d*\\b|Philippines|è²å¾‹å®¾)"
emoji = "ğŸ‡µğŸ‡­"

[[emojis.emoji]]
match = "(Pakistan|å·´åŸºæ–¯å¦)"
emoji = "ğŸ‡µğŸ‡°"

[[emojis.emoji]]
match = "(?i:\\bP[O]?L\\b|Poland|æ³¢å…°)"
emoji = "ğŸ‡µğŸ‡±"

[[emojis.emoji]]
match = "(å·´æ‹¿é©¬|Panama)"
emoji = "ğŸ‡µğŸ‡¦"

[[emojis.emoji]]
match = "(ç§˜é²|Peru)"
emoji = "ğŸ‡µğŸ‡ª"

[[emojis.emoji]]
match = "(è‘¡è„ç‰™|Portugal)"
emoji = "ğŸ‡µğŸ‡¹"

[[emojis.emoji]]
match = "(Romania|ç½—é©¬å°¼äºš)"
emoji = "ğŸ‡·ğŸ‡´"

[[emojis.emoji]]
match = "(å¡å°”ç»´äºš|Serbia)"
emoji = "ğŸ‡·ğŸ‡¸"

[[emojis.emoji]]
match = "(?i:\\bRU[S]?\\d*\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„)"
emoji = "ğŸ‡·ğŸ‡º"

[[emojis.emoji]]
match = "(Arabia|æ²™ç‰¹)"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emojis.emoji]]
match = "(Sweden|ç‘å…¸)"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emojis.emoji]]
match = "(æ–¯æ´›æ–‡å°¼äºš|Slovenia)"
emoji = "ğŸ‡¸ğŸ‡®"

[[emojis.emoji]]
match = "(æ–¯æ´›ä¼å…‹|Slovensko)"
emoji = "ğŸ‡¸ğŸ‡°"

[[emojis.emoji]]
match = "(Thailand|æ³°å›½|æ›¼è°·)"
emoji = "ğŸ‡¹ğŸ‡­"

[[emojis.emoji]]
match = "(çªå°¼æ–¯|Tunisia)"
emoji = "ğŸ‡¹ğŸ‡³"

[[emojis.emoji]]
match = "(Turkey|TÃ¼rkiye|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”)"
emoji = "ğŸ‡¹ğŸ‡·"

[[emojis.emoji]]
match = "(ä¹Œæ‹‰åœ­|Uruguay)"
emoji = "ğŸ‡ºğŸ‡¾"

[[emojis.emoji]]
match = "(Vietnam|è¶Šå—)"
emoji = "ğŸ‡»ğŸ‡³"

[[emojis.emoji]]
match = "(Africa|å—é)"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emojis.emoji]]
match = "(Ukraine|UA|ä¹Œå…‹å…°)"
emoji = "ğŸ‡ºğŸ‡¦"

[[emojis.emoji]]
match = "(Puerto.*?Rico|æ³¢å¤šé»å„)"
emoji = "ğŸ‡µğŸ‡·"

[[emojis.emoji]]
match = "(Ecuador|å„ç“œå¤šå°”)"
emoji = "ğŸ‡ªğŸ‡¨"


[[emojis.emoji]]
match = "(Morocco|æ‘©æ´›å“¥)"
emoji = "ğŸ‡²ğŸ‡¦"


[[emojis.emoji]]
match = "(Nepal|å°¼æ³Šå°”)"
emoji = "ğŸ‡³ğŸ‡µ"


[[emojis.emoji]]
match = "(Bengal|å­ŸåŠ æ‹‰)"
emoji = "ğŸ‡§ğŸ‡©"

[[emojis.emoji]]
match = "(?i:\\bC[H]?N\\b|China|back|å›å›½|ä¸­å›½[^-]|æ±Ÿè‹[^-]|åŒ—äº¬[^-]|ä¸Šæµ·[^-]|å¹¿å·[^-]|æ·±åœ³[^-]|æ­å·[^-]|å¸¸å·[^-]|å¾å·[^-]|é’å²›[^-]|å®æ³¢[^-]|é•‡æ±Ÿ[^-]|æˆéƒ½[^-]|æ²³åŒ—[^-]|å±±è¥¿[^-]|è¾½å®[^-]|å‰æ—[^-]|é»‘é¾™æ±Ÿ[^-]|æ±Ÿè‹[^-]|æµ™æ±Ÿ[^-]|å®‰å¾½[^-]|ç¦å»º[^-]|æ±Ÿè¥¿[^-]|å±±ä¸œ[^-]|æ²³å—[^-]|æ¹–åŒ—[^-]|æ¹–å—[^-]|å¹¿ä¸œ[^-]|æµ·å—[^-]|å››å·[^-]|è´µå·[^-]|äº‘å—[^-]|é™•è¥¿[^-]|ç”˜è‚ƒ[^-]|é’æµ·[^-]|å†…è’™å¤[^-]|å¹¿è¥¿[^-]|è¥¿è—[^-]|å®å¤[^-]|æ–°ç–†[^-])"
emoji = "ğŸ‡¨ğŸ‡³"

[ruleset]
enabled = true
overwrite_original_rules = false
update_ruleset_on_request = false

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "Emby"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/emby.list"

[[rulesets]]
group = "GitHub"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list"

[[rulesets]]
group = "GitHub"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/white.list"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list"

[[rulesets]]
group = "Steam"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "Steam"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "Steam"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/battlenet.list"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "EU"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/turtlewow.list"

[[rulesets]]
group = "HK"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/clubsim.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bing.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Gemini.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pandora.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list"

[[rulesets]]
group = "US"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/tmobile.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/yahngming/rules/master/direct.list"

[[rulesets]]
group = "GLOBAL"
ruleset = "[]FINAL"

[[custom_groups]]
name = "Emby"
type = "select"
rule = ["(Emby|è‡ªå»º|å®éªŒ|æ—¥ç”¨|ç¦åˆ©|TEST|0.1x|0.2x)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "GitHub"
type = "select"
rule = ["(è‡ªå»º|å®éªŒ|æ—¥ç”¨|ç¦åˆ©|TEST|0.1x|0.2x)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "Netflix"
type = "select"
rule = ["(ğŸ‡¦ğŸ‡·|ğŸ‡µğŸ‡°|ğŸ‡¹ğŸ‡·|è‡ªå»º|å®éªŒ|æ—¥ç”¨|ç¦åˆ©|TEST|0.1x|0.2x)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "Steam"
type = "select"
rule = ["(ğŸ‡¦ğŸ‡·|ğŸ‡µğŸ‡°|ğŸ‡¹ğŸ‡·|è‡ªå»º|å®éªŒ|æ—¥ç”¨|ç¦åˆ©|TEST|0.1x|0.2x)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "YouTube"
type = "select"
rule = ["(ğŸ‡¦ğŸ‡·|ğŸ‡®ğŸ‡³|ğŸ‡³ğŸ‡¬|è‡ªå»º|å®éªŒ|æ—¥ç”¨|ç¦åˆ©|TEST|0.1x|0.2x)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "EU"
type = "select"
rule = ["(ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡³ğŸ‡±|ğŸ‡ªğŸ‡¸|ğŸ‡¬ğŸ‡§)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "HK"
type = "select"
rule = ["(ğŸ‡­ğŸ‡°)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "JP"
type = "select"
rule = ["(ğŸ‡¯ğŸ‡µ)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "US"
type = "select"
rule = ["(ğŸ‡ºğŸ‡¸)", "[]GLOBAL", "[]DIRECT"]

[[custom_groups]]
name = "GLOBAL"
type = "select"
rule = [".*", "[]DIRECT"]

[[aliases]]
uri = "/v"
target = "/version"

[[aliases]]
uri = "/clash"
target = "/sub?target=clash"

[[aliases]]
uri = "/clashr"
target = "/sub?target=clashr"

[[aliases]]
uri = "/surge"
target = "/sub?target=surge"

[[aliases]]
uri = "/quan"
target = "/sub?target=quan"

[[aliases]]
uri = "/quanx"
target = "/sub?target=quanx"

[[aliases]]
uri = "/mellow"
target = "/sub?target=mellow"

[[aliases]]
uri = "/surfboard"
target = "/sub?target=surfboard"

[[aliases]]
uri = "/loon"
target = "/sub?target=loon"

[[aliases]]
uri = "/singbox"
target = "/sub?target=singbox"

[[aliases]]
uri = "/ss"
target = "/sub?target=ss"

[[aliases]]
uri = "/ssd"
target = "/sub?target=ssd"

[[aliases]]
uri = "/sssub"
target = "/sub?target=sssub"

[[aliases]]
uri = "/ssr"
target = "/sub?target=ssr"

[[aliases]]
uri = "/v2ray"
target = "/sub?target=v2ray"

[[aliases]]
uri = "/trojan"
target = "/sub?target=trojan"

[server]
listen = "0.0.0.0"
port = 25500
serve_file_root = "web"

[template]
template_path = ""

[[template.globals]]
key = "clash.http_port"
value = "7890"

[[template.globals]]
key = "clash.socks_port"
value = "7891"

[[template.globals]]
key = "clash.allow_lan"
value = "true"

[[template.globals]]
key = "clash.log_level"
value = "warn"

[[template.globals]]
key = "clash.external_controller"
value = "127.0.0.1:9090"

[[template.globals]]
key = "singbox.allow_lan"
value = "true"

[[template.globals]]
key = "singbox.mixed_port"
value = "2080"

[advanced]
log_level = "warn"
print_debug_info = true
max_pending_connections = 10240
max_concurrent_threads = 2
max_allowed_rulesets = 0
max_allowed_rules = 0
max_allowed_download_size = 0
enable_cache = true
cache_subscription = 300
cache_config = 60
cache_ruleset = 21600
script_clean_context = true
async_fetch_ruleset=false
skip_failed_links=false
