force_keyboard_focus = true
hide_quick_activation = true
theme = "default"

[providers]
default = [
	"calc",
	"desktopapplications",
	"websearch",
]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"
